### ISSUE TITLE
Wrong Color using PiCapture and opencv-------Solved------by running 'sudo raspi-update'

### ISSUE THREAD

**Issue by 541380000** [orgicus/PiCapture#1]
Dear author:
    I am using PiCapture and I met with some problem.
    I run 
`raspistill -o image.jpg`
   in the Terminal of Raspberry Pi, and get a good picture.
    But when I use the PiCapture simply capture a Mat and use imshow to show it .But  the video is blue, All the red color disappeared. I tried the color_callback() in the README.MD, but it cannot be compiled, and the error is : "image" is not decleared in the scope.
    Could you please help me with that? My e-mail is 1327804001@qq.com.
    
    and I have just solved the problem by running 'sudo raspi-update'.  
    That is it.

**Comment by 541380000** [comment]
I have just found that, blue things is red in the video,and red things and yellow things is light blue in the video.
by the way ,I am using Raspberry pi 3B

**Comment by 541380000** [comment]
and I just tried to get image only with Opencv, and get the normal video. However I want to adjust the Saturation and Contrast and so on. So I have to find out the problem.

**Comment by 541380000** [comment]
Dear author: 
    I have solved the problem by using sudo raspi-update ,which is in the README.MD.

**Comment by orgicus** [comment]
@541380000 It sounded like a colour space inversion (RGB/BGR), but very happy to hear you have found the solution in the readme file. Well done and thank you for patiently going through the readme
